### ISSUE TITLE
Can't invoke SRC7 metadata method from the rust SDK due to arbitrary nesting of heap types

### ISSUE THREAD

**Issue by cold-briu** [FuelLabs/sway-standards#38]
#### Description
Can't invoke SRC7 metadata method from the rust SDK due to [arbitrary nesting of heap types
](https://github.com/FuelLabs/fuels-rs/issues/1046) Since `metadata` Returns an Option wrapping an Enum that evaluate to string.

```
let meta = contract_instance
        .methods()
        .metadata(asset_id, "key".to_string())
        .simulate()
        .await
        .unwrap();
```
Throws the following error: 

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidType("Enums currently support only one level deep heap types.")
```

contract_instance comes from the following implementation:

```
contract;

use src_7::{Metadata, SRC7};
use std::{call_frames::contract_id, hash::Hash, storage::storage_string::*, string::String};

impl SRC7 for Contract {
    #[storage(read)]
    fn metadata(asset: AssetId, key: String) -> Option<Metadata> {
        if key == String::from_ascii_str("key") {
            Some(Metadata::String(String::from_ascii_str("value")))
        } else {
            None
        }
    }
}
```

Then, the execution should return something like:

```
let result: Option<Enum<String>> = SRC7.metadata(myAsset, myKey);
```

Considering:

```
/// Universal return type for metadata.
pub enum Metadata {
    // Used when the stored metadata is a `b256`.
    B256: b256,
    /// Used when the stored metadata is `Bytes`.
    Bytes: Bytes,
    /// Used when the stored metadata is a `u64`.
    Int: u64,
    /// Used when the stored metadata is a `String`.
    String: String,
}
```

Is this an implementation error, sdk limitation o src7 error? 🤔

**Comment by bitzoic** [comment]
This is an SDK limitation

**Comment by mpoplavkov** [comment]
Could this be resolved either in the standard or on the SDK side? That's important for ecosystem projects if you want them to support the standard
@cold-briu 
@bitzoic

**Comment by cold-briu** [comment]
cc @digorithm

**Comment by cold-briu** [comment]
Closing since it's out of scope: SDK Limitation. 
Please check [fuels-rs/issues/1213](https://github.com/FuelLabs/fuels-rs/issues/1213).
