### ISSUE TITLE
docs: Specifying tagged version does not work in forc.toml

### ISSUE THREAD

**Issue by calldelegation** [FuelLabs/sway-standards#49]
As outlined in the forum post [here](https://forum.fuel.network/t/sway-token-standarts-documentation/3896)

In `forc.toml` `#1` does not work but `#2` does

1. `src20 = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.2.2" }`

```
Error: failed to find package `src20` in git+https://github.com/FuelLabs/sway-standards?tag=v0.1.1#5a85090678f3a9deb7040424d4ee502d3d9f5bcf
```

2. `src20 = { git = "https://github.com/FuelLabs/sway-standards" }`

```
Fetching src20 git+https://github.com/FuelLabs/sway-standards?default-branch#718d51fdfdbdf4d399c8f281e31462a9f35f0304
Creating a new `Forc.lock` file. (Cause: lock file did not match manifest)
  Adding src20 git+https://github.com/FuelLabs/sway-standards?default-branch#718d51fdfdbdf4d399c8f281e31462a9f35f0304
 Created new lock file at /Users/calldelegation/Projects/Fuel/hello_sway/Forc.lock
 ```

**Comment by bitzoic** [comment]
This is the result of https://github.com/FuelLabs/sway-standards/pull/47. In that PR we changed the import from `src_20` to `src20`. No release has been made.

In example 1, the import should be `src_20`. This uses the most recent stable release.

In example 2, you are pulling from master. There is no release yet.

**Comment by bitzoic** [comment]
A new release has been made: https://github.com/FuelLabs/sway-standards/releases/tag/v0.3.0
