### ISSUE TITLE
SRC-3; Mint and Burn Standard

### ISSUE THREAD

**Issue by bitzoic** [FuelLabs/sway-standards#6]
### Motivation

# Abstract

The following standard enables the minting and burning of tokens for any fungible assets within the Sway Language. It seeks to define mint and burn functions defined separately from the [SRC-20](https://github.com/FuelLabs/sway-standards/issues/1) standard. Any contract that implements the SRC-3 standard MUST implement the [SRC-20](https://github.com/FuelLabs/sway-standards/issues/1) standard.

# Motivation

The intent of this standard is to separate the extensions of minting and burning from the [SRC-20](https://github.com/FuelLabs/sway-standards/issues/1) standard.

# Prior Art

Minting and burning were initially added to the [SRC-20](https://github.com/FuelLabs/sway-standards/issues/1) standard.

# Specification

## Required Public Functions

The following functions MUST be implemented to follow the SRC-3 standard:

### `fn mint(recipient: Identity,  sub_id: b256, amount: u64)`
This function MUST mint `amount` tokens of type `sub_id` and transfer them to the `recipient`. This function MAY contain arbitrary conditions for minting, and revert if those conditions are not met.
##### Arguments
* `recipient` - The `Identity` to which the newly minted tokens are transferred to.
* `sub_id` - The token type to mint.
* `amount` - The quantity of tokens to mint.
##### Events
This function MUST emit the `Mint` event.

### `fn burn(sub_id: b256)`
This function MUST burn all tokens sent to the contract in this function invocation. 
##### Events
This function MUST emit the `Burn` event.

## Events

The following events MUST be emitted to follow the SRC-3 standard:

### `Mint`
This event MUST be emitted when the `std::token::mint` function is called either directly or indirectly. 
##### Arguments
* `recipient` - The `Identity` to which the newly minted tokens are transferred to.
* `asset` - The ID of the asset that was minted.
* `amount` - The quantity of tokens minted.
```rust
struct Mint {
    recipient: Identity,
    asset: b256,
    amount: u64,
}
```

### `Burn` 
This event MUST be emitted then the `std::token::burn` function is called either directly or indirectly.
##### Argument
* `sender` - The `Identity` which sent the tokens to the contract to burn.
* `sub_id` - The ID of the asset that was burned.
* `amount` - The quantity of tokens burned.
```rust
struct Burn {
     sender: Identity,
     sub_id: b256,
     amount: u64,
}
```

# Rationale

This standard has been added to enable compatibility between applications and allow minting and burning tokens per use case. This standard has been separated from the [SRC-20](https://github.com/FuelLabs/sway-standards/issues/1) standard to allow for the minting and burning for all fungible tokens, irrelevant of whether they are [Native Assets](https://fuellabs.github.io/sway/v0.38.0/book/blockchain-development/native_assets.html) or not.

# Backwards Compatibility

This standard is compatible with Fuel's [Native Assets](https://fuellabs.github.io/sway/v0.38.0/book/blockchain-development/native_assets.html) ensuring it's compatibility for both the [SRC-20](https://github.com/FuelLabs/sway-standards/issues/1) standard and the [SRC-721(https://github.com/FuelLabs/sway-standards/issues/2) standard.

# Security Considerations

This standard may introduce security considerations if the mint function does not include any checks to ensure the calling of the `mint()` function is deemed valid or permitted. Checks are highly encouraged.
The burn function may also introduce a security consideration if the total supply within the [SRC-20](https://github.com/FuelLabs/sway-standards/issues/1) standard is not modified.

# Example ABI

```rust
abi MyTokenSRC3 {
    fn mint(recipient: Identity, asset: b256, amount: u64);
    fn burn(asset: b256);
}
```

This draft standard is to be released as `v0.1`.

**Comment by SwayStar123** [comment]
mint and burn MUST update total_supply. Please add that aswell
