### ISSUE TITLE
SRC-20 broken example links

### ISSUE THREAD

**Issue by MoMannn** [FuelLabs/sway-standards#77]
### Motivation

SRC-20 example links for single and multi are broken:

https://github.com/FuelLabs/sway-standards/blob/master/SRCs/src-20.md#example-implementation

**Comment by MoMannn** [comment]
Actually all SRC standard that have linking examples have the example links broken.

**Comment by bitzoic** [comment]
Resolved by https://github.com/FuelLabs/sway-standards/pull/81
